#ifndef __HELPER__
#define __HELPER__

#include <elf.h>
#include <string.h>

#define SECTION_ITEM(X) [X] = #X

#define SECTION_TYPE_MAP(TYPE) (((TYPE) >= 20) ? ("SHT_UNKOWN") \
    : (SECTION_TYPE_TABLE[(TYPE)]))

static const char *SECTION_TYPE_TABLE[20] = {
    SECTION_ITEM(SHT_NULL),
    SECTION_ITEM(SHT_PROGBITS),
    SECTION_ITEM(SHT_SYMTAB),
    SECTION_ITEM(SHT_STRTAB),
    SECTION_ITEM(SHT_RELA),
    SECTION_ITEM(SHT_HASH),
    SECTION_ITEM(SHT_DYNAMIC),
    SECTION_ITEM(SHT_NOTE),
    SECTION_ITEM(SHT_NOBITS),
    SECTION_ITEM(SHT_REL),
    SECTION_ITEM(SHT_SHLIB),
    SECTION_ITEM(SHT_DYNSYM),
    SECTION_ITEM(SHT_INIT_ARRAY),
    SECTION_ITEM(SHT_FINI_ARRAY),
    SECTION_ITEM(SHT_PREINIT_ARRAY),
    SECTION_ITEM(SHT_GROUP),
    SECTION_ITEM(SHT_SYMTAB_SHNDX),
    SECTION_ITEM(SHT_NUM)
};

#endif
